name: todo_flutter
description: A minimal local Todo app foundation for Android and iOS.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.31.0
  drift_flutter: ^0.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.31.0
  build_runner: ^2.15.1

flutter:
  uses-material-design: true
  fonts:
    - family: VT323
      fonts:
        - asset: assets/fonts/vt323.ttf